apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appOfApps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Well5a/todolist-argocd.git
    targetRevision: HEAD
    path: features
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
