apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolistF1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Well5a/todolist-config.git
    targetRevision: feature/0001
    path: minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-application-f1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
